apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: nguyendumbo/fe:latest
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
