apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-deployment
  template:
    metadata:
      labels:
        app: fe-deployment
    spec:
      containers:
      - name: fe
        image: nguyendumbo/fe:latest
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 32000
  selector:
    app: fe-deployment