apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            env:
              - name: MongoAuditConnectionString
                value: {{ .Values.env.MongoAuditConnectionString | quote }}
              - name: MongoDBUserSessionDatabaseName
                value: {{ .Values.env.MongoDBUserSessionDatabaseName | quote }}
          restartPolicy: OnFailure
