apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be-deployment
  template:
    metadata:
      labels:
        app: be-deployment
    spec:
      containers:
      - name: be
        image: nguyendumbo/be:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
